general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm.256color"

[font]
normal = { family = "RobotoMono Nerd Font", style = "Medium" }
size = 9

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]

[window]
dimensions = { columns = 80, lines = 30 }

